[package]
name = "gtk-first"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15"
# gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
